import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import React from "react";
import { ToastContainer } from "react-toastify";
import Loading from "./[lang]/loading";

export const metadata: Metadata = {
  title: "Tender Admin",
  description: "Generated by Grandmart",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang}>
      <body suppressHydrationWarning={true} className="custom-scrollbar">
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
          <ToastContainer />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </div>
      </body>
    </html>
  );
}
